sonar.projectKey=devsecops-pipeline
sonar.projectName=DevSecOps Pipeline
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true
