{
 "title": "DevSecOps App",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests / sec",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(app_requests_total[1m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "p95 latency (s)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_request_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "5xx error ratio",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 8, "h": 6 },
   "targets": [
    {
     "expr": "sum(rate(app_requests_total{status=~\"5..\"}[5m])) / sum(rate(app_requests_total[5m]))"
    }
   ]
  },
  {
   "title": "Pods up",
   "type": "stat",
   "gridPos": { "x": 8, "y": 8, "w": 8, "h": 6 },
   "targets": [
    {
     "expr": "sum(up{job=\"devsecops-app\"})"
    }
   ]
  }
 ]
}